version: '2.2'

networks:
  lk-shared:
    driver: local

volumes:
  db-volume:
    driver: local
  gae-storage:
    driver: local

services:
  backend:
    image: viktorkifer/launchkit-app:1.0.0
    restart: unless-stopped
    environment:
      PORT: 9101
      POSTGRES_HOST: postgres
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: MySecretKey
      C_FORCE_ROOT: "true"
      # these are optional
      EMAIL_SMTP_HOST:
      EMAIL_SMTP_USER:
      EMAIL_SMTP_PASSWORD:
      EMAIL_FROM_DOMAIN: yoursite.com
      SLACK_CLIENT_ID:
      SLACK_CLIENT_SECRET:
    networks:
      - lk-shared
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      gae:
        condition: service_started
    ports:
      - 9101:9101
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9101/v1/debug/health_check"]
      interval: 10s
      timeout: 15s
      retries: 6

  gae:
    image: viktorkifer/launchkit-gae:1.0.0
    restart: unless-stopped
    environment:
      SERVER_SOFTWARE: Dev
    networks:
      - lk-shared
    volumes:
      - gae-storage:/usr/src/app/.dev_gae_storage
    ports:
      - 9102:9102
      - 9104:9104
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9102"]
      interval: 10s
      timeout: 15s
      retries: 6

  reviews:
    image: viktorkifer/launchkit-reviews:1.0.0
    restart: unless-stopped
    environment:
      PORT: 9101
      POSTGRES_HOST: postgres
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: MySecretKey
      # these are optional
      EMAIL_SMTP_HOST:
      EMAIL_SMTP_USER:
      EMAIL_SMTP_PASSWORD:
      EMAIL_FROM_DOMAIN: yoursite.com
      SLACK_CLIENT_ID:
      SLACK_CLIENT_SECRET:
    networks:
      - lk-shared
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  skit:
    image: viktorkifer/launchkit-skit:1.0.0
    restart: unless-stopped
    environment:
      API_HOST: http://backend:9101/
      DEBUG: 'true'
      PORT: 9100
    depends_on:
      - backend
    networks:
      - lk-shared
    ports:
      - 9100:9100
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9100"]
      interval: 10s
      timeout: 15s
      retries: 6

  redis:
    image: redis:4-alpine
    restart: unless-stopped
    networks:
      - lk-shared
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: viktorkifer/launchkit-postgres-hstore:1.0.0
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - lk-shared
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 30s
      retries: 6
